// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright 2018-2021 NXP
 */

#include <string.h>
#include <stdio.h>
#include <util.h>

#include <ta_crypto_perf.h>

const uint32_t id_alg_list[] = {
	TEE_ALG_AES_ECB_NOPAD,
	TEE_ALG_AES_CBC_NOPAD,
	TEE_ALG_AES_CTR,
	TEE_ALG_AES_CTS,
	TEE_ALG_AES_XTS,
	TEE_ALG_AES_CBC_MAC_NOPAD,
	TEE_ALG_AES_CBC_MAC_PKCS5,
	TEE_ALG_AES_CMAC,
	TEE_ALG_AES_CCM,
	TEE_ALG_AES_GCM,
	TEE_ALG_DES_ECB_NOPAD,
	TEE_ALG_DES_CBC_NOPAD,
	TEE_ALG_DES_CBC_MAC_NOPAD,
	TEE_ALG_DES_CBC_MAC_PKCS5,
	TEE_ALG_DES3_ECB_NOPAD,
	TEE_ALG_DES3_CBC_NOPAD,
	TEE_ALG_DES3_CBC_MAC_NOPAD,
	TEE_ALG_DES3_CBC_MAC_PKCS5,
	TEE_ALG_RSASSA_PKCS1_V1_5_MD5,
	TEE_ALG_RSASSA_PKCS1_V1_5_SHA1,
	TEE_ALG_RSASSA_PKCS1_V1_5_SHA224,
	TEE_ALG_RSASSA_PKCS1_V1_5_SHA256,
	TEE_ALG_RSASSA_PKCS1_V1_5_SHA384,
	TEE_ALG_RSASSA_PKCS1_V1_5_SHA512,
	TEE_ALG_RSASSA_PKCS1_V1_5_MD5SHA1,
	TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA1,
	TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA224,
	TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256,
	TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA384,
	TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA512,
	TEE_ALG_RSAES_PKCS1_V1_5,
	TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
	TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA224,
	TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA256,
	TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA384,
	TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA512,
	TEE_ALG_RSA_NOPAD,
	TEE_ALG_DSA_SHA1,
	TEE_ALG_DSA_SHA224,
	TEE_ALG_DSA_SHA256,
	TEE_ALG_DH_DERIVE_SHARED_SECRET,
	TEE_ALG_MD5,
	TEE_ALG_SHA1,
	TEE_ALG_SHA224,
	TEE_ALG_SHA256,
	TEE_ALG_SHA384,
	TEE_ALG_SHA512,
	TEE_ALG_MD5SHA1,
	TEE_ALG_HMAC_MD5,
	TEE_ALG_HMAC_SHA1,
	TEE_ALG_HMAC_SHA224,
	TEE_ALG_HMAC_SHA256,
	TEE_ALG_HMAC_SHA384,
	TEE_ALG_HMAC_SHA512,
	TEE_ALG_ECDSA_P192,
	TEE_ALG_ECDSA_P224,
	TEE_ALG_ECDSA_P256,
	TEE_ALG_ECDSA_P384,
	TEE_ALG_ECDSA_P521,
	TEE_ALG_ECDH_P192,
	TEE_ALG_ECDH_P224,
	TEE_ALG_ECDH_P256,
	TEE_ALG_ECDH_P384,
	TEE_ALG_ECDH_P521
};

const char *name_alg_list[] = {
	"AES_ECB_NOPAD",
	"AES_CBC_NOPAD",
	"AES_CTR",
	"AES_CTS",
	"AES_XTS",
	"AES_CBC_MAC_NOPAD",
	"AES_CBC_MAC_PKCS5",
	"AES_CMAC",
	"AES_CCM",
	"AES_GCM",
	"DES_ECB_NOPAD",
	"DES_CBC_NOPAD",
	"DES_CBC_MAC_NOPAD",
	"DES_CBC_MAC_PKCS5",
	"DES3_ECB_NOPAD",
	"DES3_CBC_NOPAD",
	"DES3_CBC_MAC_NOPAD",
	"DES3_CBC_MAC_PKCS5",
	"RSASSA_PKCS1_V1_5_MD5",
	"RSASSA_PKCS1_V1_5_SHA1",
	"RSASSA_PKCS1_V1_5_SHA224",
	"RSASSA_PKCS1_V1_5_SHA256",
	"RSASSA_PKCS1_V1_5_SHA384",
	"RSASSA_PKCS1_V1_5_SHA512",
	"RSASSA_PKCS1_V1_5_MD5SHA1",
	"RSASSA_PKCS1_PSS_MGF1_SHA1",
	"RSASSA_PKCS1_PSS_MGF1_SHA224",
	"RSASSA_PKCS1_PSS_MGF1_SHA256",
	"RSASSA_PKCS1_PSS_MGF1_SHA384",
	"RSASSA_PKCS1_PSS_MGF1_SHA512",
	"RSAES_PKCS1_V1_5",
	"RSAES_PKCS1_OAEP_MGF1_SHA1",
	"RSAES_PKCS1_OAEP_MGF1_SHA224",
	"RSAES_PKCS1_OAEP_MGF1_SHA256",
	"RSAES_PKCS1_OAEP_MGF1_SHA384",
	"RSAES_PKCS1_OAEP_MGF1_SHA512",
	"RSA_NOPAD",
	"DSA_SHA1",
	"DSA_SHA224",
	"DSA_SHA256",
	"DH_DERIVE_SHARED_SECRET",
	"MD5",
	"SHA1",
	"SHA224",
	"SHA256",
	"SHA384",
	"SHA512",
	"MD5SHA1",
	"HMAC_MD5",
	"HMAC_SHA1",
	"HMAC_SHA224",
	"HMAC_SHA256",
	"HMAC_SHA384",
	"HMAC_SHA512",
	"ECDSA_P192",
	"ECDSA_P224",
	"ECDSA_P256",
	"ECDSA_P384",
	"ECDSA_P521",
	"ECDH_P192",
	"ECDH_P224",
	"ECDH_P256",
	"ECDH_P384",
	"ECDH_P521"
};

uint32_t get_nb_algo(void)
{
	return ARRAY_SIZE(id_alg_list);
}

uint32_t get_size_name_alg_list(void)
{
	uint32_t idx;
	uint32_t size = 0;

	for (idx = 0; idx < get_nb_algo(); idx++)
		size += (strlen(name_alg_list[idx]) + 1);

	return size;
}

void copy_name_alg_list(char *buffer)
{
	uint32_t idx;
	uint32_t size;

	for (idx = 0; idx < get_nb_algo(); idx++) {
		size = (strlen(name_alg_list[idx]) + 1);
		memcpy(buffer, name_alg_list[idx], size);
		buffer += size;
	}
}

uint32_t get_alg_id(char *name, size_t size)
{
	uint32_t idx;

	for (idx = 0; idx < get_nb_algo(); idx++) {
		if (!(strncmp(name_alg_list[idx], name, size)))
			return id_alg_list[idx];
	}

	return (uint32_t)(-1);
}
